---
- hosts: dev
  tasks:
    - name: Install httpd package
      yum:
        name: httpd
        state: latest
    - name: Copy index file to /var/www/html/
      become: yes
      copy:
        src: index.html
        dest: /var/www/html
    - name: Copy httpd.conf file to /etc/httpd/conf
      become: yes
      copy:
        src: httpd.conf
        dest: /etc/httpd/conf
    - name: restart httpd service
      become: yes
      service:
        name: httpd
        state: restarted
